apps:
    - script: bin/cli.js
      name: huectl-server
      watch: true
      ignore_watch:
        - src
        - node_modules
      env:
        HUE_ACCOUNT: wwDrY4zCLgpzB1EZKoPEnCWLohOojH3CSV85QGIK
    - script: node_modules/.bin/tsc
      args: --watch
      name: huectl-typescript
